name: Build Clang and LLVM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ninja & Aria2
        run: sudo apt-get update && sudo apt-get install -y ninja-build aria2

      - name: Build
        shell: bash
        run: |
          ./build-clang.sh
      
      - name: Inspect
        shell: bash
        run: |
          PATH=llvm-project/build/destdir/bin:llvm-project/build/destdir/usr/bin:$PATH llvm-config --version
          PATH=llvm-project/build/destdir/bin:llvm-project/build/destdir/usr/bin:$PATH clang --version

      - name: Zip
        shell: bash
        run: |
          mkdir -p dist
          tar --directory llvm-project/build/destdir --create --xz --verbose --file dist/llvm.tar.xz .
          ls -lh dist/llvm.tar.xz

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: llvm-linux-amd64
          path: dist
          if-no-files-found: error
          retention-days: 1
