name: Build Clang and LLVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LLVM source
        run: |
          git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          git checkout main  # Or specify a version/tag/branch

      - name: Build LLVM and Clang
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" \
            -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="host" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_LTO=Thin \
            ../llvm-project/llvm
          ninja

      - name: Upload Clang binaries
        uses: actions/upload-artifact@v3
        with:
          name: clang-binaries
          path: |
            build/bin/clang*
            build/lib/clang
            build/include/clang
