name: Build Clang and LLVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build xz-utils

      - name: Set up LLVM source
        run: |
          git clone --depth=1 https://github.com/llvm/llvm-project.git
          # cd llvm-project
          # git checkout main  # Or specify a version/tag/branch

      - name: Build LLVM and Clang
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLLVM_ENABLE_PROJECTS="clang;lld" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_BUILD_TOOLS=OFF \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt" \
            -DLLVM_ENABLE_LTO=Full \
            ../llvm-project/llvm
          ninja -j $(nproc)

      - name: Compress build artifacts
        run: |
          # Create a tarball and compress it with xz for better compression
          tar -cf build-artifacts.tar build/bin build/lib build/include
          xz -z build-artifacts.tar

      - name: Upload Clang binaries
        uses: actions/upload-artifact@v3
        with:
          name: clang-binaries
          path: build-artifacts.tar.xz
